### ISSUE TITLE
Shiny script dependencies 

### ISSUE THREAD

**Issue by zx8754** [duncantl/CodeDepends#13]
Would it be possible to supply 3 files:

- global.R
- ui.R
- server.R

And get network plot of all dependencies of variables, including static like `x = 1 + y` and dynamic like `input$myChoice`, `myData <- reactive({ ... })`, `output$myTable <- renderDataTable( ... )`?

**Comment by duncantl** [comment]
Yes, CodeDepends basically collects the information you need for this. (It does not deal with closures).  However, you will have to assemble the information that you want using the functions in the package.

**Comment by zx8754** [comment]
Will explore more. Thank you for the package!
