### ISSUE TITLE
visNetwork + directed layouts

### ISSUE THREAD

**Issue by wlandau-lilly** [duncantl/CodeDepends#18]
I am really enjoying the graphing features of CodeDepends, especially the networks of relationships among the functions of new packages I am learning. It makes me think about some new things that would be nice to see in the future.

1. I am a big fan of the interactivity in `visNetwork`, especially for large graphs. I believe `igraph` can serve as an intermediary if you decide to port `Rgraphviz` graphs to `visNetwork`.
2. It would be helpful and visually pleasing to see directed layouts as in `visHierarchicalLayout(sortMethod = "directed")`. Chasing paths around the screen with my eyes can be difficult.

**Comment by duncantl** [comment]
We'd gladly entertain patches.

**Comment by wlandau-lilly** [comment]
Uptake's [`pkgnet`](https://github.com/UptakeOpenSource/pkgnet) package is making this a major focus. It [currently has problems with its function networks](https://github.com/UptakeOpenSource/pkgnet/issues/79), so I recommended that they use `CodeDepends::makeCallGraph()` in the backend.
