### ISSUE TITLE
 Bad link

### ISSUE THREAD

**Issue by jessjaco** [duncantl/CodeDepends#6]
Link to http://www.omegahat.org/CodeDepends returns 404

**Comment by omegahat** [comment]
That should be omegahat.net rather than .org.
In what document did you encounter this link?
Thanks - Duncan

**Comment by jessjaco** [comment]
It's near the top of https://github.com/duncantl/CodeDepends in a browser: 
<img width="799" alt="screen shot 2017-01-10 at 9 03 34 am" src="https://cloud.githubusercontent.com/assets/1250693/21813501/b94dc2f4-d713-11e6-9781-8730945cd059.png">

**Comment by duncantl** [comment]
Aaah, thanks.  Fixed now.
