### ISSUE TITLE
Prepare for CRAN release

### ISSUE THREAD

**Issue by gmbecker** [duncantl/CodeDepends#9]
All,

I would like torelease a package that depends on CodeDepends to CRAN in concert with submitting manuscript about it to a journal. Are there any objections to me preparing CodeDepends for release (ie cleaning up docs, making sure it passes check, etc)  and submitting it to CRAN?

Is there any local work you have that you'd like to merge in before the release? @duncantl @nick-ulle @clarkfitzg

**Comment by clarkfitzg** [comment]
Fine by me. I appreciate the heads up.

**Comment by dsidavis** [comment]
Gabe, please go ahead and clean up. Let us know of any significant changes, but otherwise great. 
Who can argue against others doing the clean up :-)
Thanks

**Comment by gmbecker** [comment]
CodeDepends 0.5-3 is now on CRAN.
